version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pokefactory_db
    environment:
      POSTGRES_DB: ${DB_NAME:-pokefactory}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokefactory_network
    restart: unless-stopped

  backend:
    image: yourusername/pokefactory-server:latest
    container_name: pokefactory_backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-pokefactory}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - API_PORT=${API_PORT:-8080}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    ports:
      # Minecraft server access (localhost only - secure)
      - "127.0.0.1:${API_PORT:-8080}:8080"
      # Web dashboard access (public - for webapp)
      - "${WEB_PORT:-8081}:8080"
    depends_on:
      - postgres
    networks:
      - pokefactory_network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pokefactory_network:
    driver: bridge